name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  full-docker-compose-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker Compose version
        run: docker compose version

      - name: Build and Start Full Stack
        run: |
          docker compose up -d --build

      - name: Wait for containers to be ready
        run: |
          echo "⏳ Waiting for services to boot..."
          sleep 30

      - name: Run Prisma Migrations (via prisma-manager)
        run: |
          docker compose exec prisma-manager npx prisma migrate dev --schema=prisma/schema.prisma

      - name: Run Tests inside test-manager
        run: |
          docker compose exec test-manager npm run test:all

      - name: Shutdown docker-compose
        if: always()
        run: |
          docker compose down -v
