name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  full-docker-compose-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker Compose version
        run: docker compose version

      - name: Create env files from GitHub Secrets
        run: |
          mkdir -p api/envs
          echo "${{ secrets.ENV_DB }}" > api/envs/.env-db
          echo "${{ secrets.ENV_API }}" > api/envs/.env-api

      - name: Build and Start Full Stack
        run: |
          docker compose -f api/docker-compose.yml up -d --build

      - name: Wait for containers to be ready
        run: |
          echo "⏳ Waiting for services to boot..."
          sleep 30

      - name: Run Prisma Migrations (via prisma-manager)
        run: |
          docker compose -f api/docker-compose.yml exec prisma-manager npx prisma migrate dev --schema=prisma/schema.prisma

      - name: Run Tests inside test-manager
        run: |
          docker compose -f api/docker-compose.yml exec test-manager npm run test:all

      - name: Shutdown docker-compose
        if: always()
        run: |
          docker compose -f api/docker-compose.yml down -v
